version: "3"

services:
  db:
    image: mysql:8.0.30-debian
    ports:
      - 3307:3306
    # env_file:
    #  - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    volumes:
      - pcalmysql:/var/lib/mysql      

volumes:
  pcalmysql: