version: "3"

services:
  app-course:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app-course
  db:
    image: mysql:8.0.30-debian
    # env_file:
    #   - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager